name: Run formatter 📝 and linter 🧹
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run-formatter-linter-tests:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        id: install-deps
        shell: pwsh
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install jinja2
          curl -o run-clang-tidy.py https://raw.githubusercontent.com/llvm/llvm-project/refs/heads/main/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py
          
      - name: CMake Configure
        id: cmake-configure
        run: |
          cmake --preset=ci-windows-x64-test -DPython_EXECUTABLE="$((get-command python3).Path)"
          cmake --build --preset=ci-windows-x64-test

      - name: Run clang-format
        id: run-clang-format
        run: |
          clang-format --verbose --dry-run -Werror @(Get-ChildItem -Recurse -File -Include '*.cpp','*.hpp' | Where-Object { $_.FullName -notmatch '\\build\\' } | ForEach-Object { $_.FullName })
          
      - name: Run clang-tidy
        id: run-clang-tidy
        if: success() || failure()
        run: |
          python3 run-clang-tidy.py -j 4 -p build -warnings-as-errors *