name: Run formatter 📝, linter 🧹 and tests 🧪
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run-formatter-linter-tests:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        id: install-deps
        shell: pwsh
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install jinja2
          curl -o run-clang-tidy.py https://raw.githubusercontent.com/llvm/llvm-project/refs/heads/main/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py

      - name: CMake Configure
        id: cmake-configure
        shell: pwsh
        run: |
          cmake --preset=windows-clang-release -DPython_EXECUTABLE="$((get-command python3).Path)"
          cmake --build --preset=windows-clang-release --parallel

      - name: Run clang-format
        id: run-clang-format
        run: |
          clang-format --verbose --dry-run -Werror @(Get-ChildItem -Recurse -File -Include '*.cpp','*.hpp' | Where-Object { $_.FullName -notmatch '\\build\\' } | ForEach-Object { $_.FullName })

      - name: Run clang-tidy
        id: run-clang-tidy
        if: success() || failure()
        run: |
          python3 run-clang-tidy.py -p build/windows-clang-release -warnings-as-errors * -use-color -quiet -header-filter "(k|m)En[\\\/]src[\\\/].*"

      - name: Run tests
        id: run-tests
        if: success() || failure()
        working-directory: ./build/windows-clang-release
        run: ctest --output-on-failure -j $env:NUMBER_OF_PROCESSORS
